### ISSUE TITLE
Update deployment on config change

### ISSUE THREAD

**Issue by rgreinho** [request-yo-racks/charts#30]
Issue Type
----------

- Feature request

Current Behavior
----------------

When only the secrets or configmap of a deployment change, the pods are not restarted.

Expected Behavior
-----------------

The pods should restart if their secrets and/or configmaps are updated.

Possible Solution
-----------------

```yaml
kind: Deployment
spec:
  template:
    metadata:
      annotations:
        checksum/config: {{ include (print $.Template.BasePath "/configmap.yaml") . | sha256sum }}
[...]
```
See [Update deployment on config change](https://github.com/kubernetes/helm/blob/master/docs/charts_tips_and_tricks.md#automatically-roll-deployments-when-configmaps-or-secrets-change).
